# It is a makefile for hw2
all:base.cpp mutex.cpp sem.cpp
	g++ base.cpp -std=c++11 -lpthread -o base.o
	g++ mutex.cpp -std=c++11 -lpthread -o mutex.o
	g++ sem.cpp -std=c++11 -lpthread -o sem.o
clean:
	rm -f base.o
	rm -f mutex.o
	rm -f sem.o
